FROM debian:buster-slim

MAINTAINER Pietro Pizzo <pietro.pizzo@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /src

RUN apt-get update && apt-get install -y texlive texlive-latex-extra texlive-lang-italian texlive-lang-english texlive-fonts-extra texlive-full texlive-extra-utils make

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /usr/share/doc* /usr/share/man/* /usr/share/info/*
